name: CI Quality Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        
      # - name: Run Linter (ESLint)   # <--- COMMENTÉ ou SUPPRIMÉ
      #   run: npm run lint

      - name: Run Tests (Jest)
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
            args: >
              -Dsonar.projectKey=tokenini_smarthealth
              -Dsonar.organization=tokiniri
              -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}